objects/Product2.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>BosniaandHerzegovina</fullName>
                </value>
                <value>
                    <fullName>Bulgaria</fullName>
                </value>
                <value>
                    <fullName>Croatia</fullName>
                </value>
                <value>
                    <fullName>Cyprus</fullName>
                </value>
                <value>
                    <fullName>CzechRepublic</fullName>
                </value>
                <value>
                    <fullName>Denmark</fullName>
                </value>
                <value>
                    <fullName>Estonia</fullName>
                </value>
                <value>
                    <fullName>Finland</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Greece</fullName>
                </value>
                <value>
                    <fullName>Hungary</fullName>
                </value>
                <value>
                    <fullName>Iceland</fullName>
                </value>
                <value>
                    <fullName>Ireland</fullName>
                </value>
                <value>
                    <fullName>Italy</fullName>
                </value>
                <value>
                    <fullName>Kazakhstan</fullName>
                </value>
                <value>
                    <fullName>Kosovo</fullName>
                </value>
                <value>
                    <fullName>Latvia</fullName>
                </value>
                <value>
                    <fullName>Liechtenstein</fullName>
                </value>
                <value>
                    <fullName>Lithuania</fullName>
                </value>
                <value>
                    <fullName>Luxembourg</fullName>
                </value>
                <value>
                    <fullName>Malta</fullName>
                </value>
                <value>
                    <fullName>Moldova</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/RF_Discount_Manager_Helper.cls
/**
 * Created by BRITENET on 23.10.2019.
 */

public class RF_Discount_Manager_Helper {

    public static List<RF_PriceBook_Item> getAllResultList(String text, List<String> ids) {
        List<Product2> products = [SELECT Id, Name, Family, Country__c, City__c, (SELECT Id, UnitPrice FROM PricebookEntries WHERE IsActive = true AND Pricebook2.IsStandard = true) FROM Product2 WHERE IsActive = true AND Id NOT IN :ids AND Name like :text];
        List<RF_PriceBook_Item> ppb = new List<RF_PriceBook_Item>();
        for (Product2 p : products) {
            RF_Flat flat = new RF_Flat(p);
            RF_PriceBook_Item priceBookItem = new RF_PriceBook_Item(flat, p.PricebookEntries.get(0).UnitPrice, 0.0, 0.0, '');
            ppb.add(priceBookItem);
        }
        return ppb;
    }

    public static List<Pricebook2> getAllPriceBooks(String recordId){
        List<Pricebook2> pricebooks = [SELECT Id, Name, StartDate__c, End_Date__c, IsStandard FROM Pricebook2 WHERE IsActive = true];
        return pricebooks;
    }

    @AuraEnabled
    public static RF_PriceBook getPriceBookDetails(String recordId){
        RF_PriceBook ppb = new RF_PriceBook();
        List<RF_PriceBook_Item> productList = new List<RF_PriceBook_Item>();
        if(!String.isBlank(recordId)){
            List<Product2> products = [SELECT Id, Name, Family, Country__c, City__c, (SELECT Id, UnitPrice, Pricebook2.Name, Pricebook2.IsStandard, Pricebook2.StartDate__c, Pricebook2.End_Date__c FROM PricebookEntries WHERE IsActive = true AND  Pricebook2Id = :recordId) FROM Product2 WHERE IsActive = true AND Id IN (SELECT Product2Id FROM PricebookEntry WHERE Pricebook2Id = :recordId)];
            for(Product2 p: products){
                RF_Flat flat = new RF_Flat(p);
                RF_PriceBook_Item priceBookItem = new RF_PriceBook_Item(flat, p.PricebookEntries.get(0).UnitPrice, 0.0, 0.0, p.PricebookEntries.get(0).Id);
                productList.add(priceBookItem);
            }
            ppb.priceBook = products.get(0).PricebookEntries.get(0).Pricebook2;
            ppb.priceBookItems = productList;
        }
        return ppb;
    }



    @AuraEnabled
    public static RF_Response_Message upsertPriceBook(RF_PriceBook priceBookRF){
        Savepoint sp = Database.setSavepoint();
        List<RF_PriceBook_Item> priceBookItems = priceBookRF.priceBookItems;
        List<String> productEntryIds = new List<String>();
        List<PricebookEntry> priceBookEntries = new List<PricebookEntry>();
        Pricebook2 pricebook = priceBookRF.priceBook;
        try {
            pricebook.IsActive = true;
            Database.upsert(pricebook);
            for (RF_PriceBook_Item item: priceBookItems) {
                PricebookEntry pricebookEntry = new PricebookEntry();
                if (!String.isBlank(item.priceBookEntryId)) {
                    productEntryIds.add(item.priceBookEntryId);
                    pricebookEntry.Id = item.priceBookEntryId;
                } else {
                    pricebookEntry.Pricebook2Id = pricebook.Id;
                    pricebookEntry.Pricebook2 = pricebook;
                    pricebookEntry.Product2Id = item.flat.product.Id;
                    pricebookEntry.Product2 = item.flat.product;
                }
                pricebookEntry.UnitPrice = item.unitPrice;
                pricebookEntry.IsActive = true;
                if(item.newUnitPrice > 0) {
                    pricebookEntry.UnitPrice = item.newUnitPrice;
                }
                if (item.newGroupUnitPrice > 0 && (item.newGroupUnitPrice < item.newUnitPrice || item.newUnitPrice == 0)) {
                    pricebookEntry.UnitPrice = item.newGroupUnitPrice;
                }
                priceBookEntries.add(pricebookEntry);
            }
            List<PricebookEntry> pricebookToDelete = [SELECT Id FROM PricebookEntry WHERE Id NOT IN :productEntryIds AND Pricebook2Id = :pricebook.Id];
            Database.delete(pricebookToDelete);
            List<Database.UpsertResult> sr = Database.upsert(priceBookEntries);
        } catch (Exception e){
            Database.rollback(sp);
            return new RF_Response_Message(Label.MESSAGE_ERROR_CODE, Label.MESSAGE_ERROR, e.getMessage());
        }
        String result = Label.MESSAGE_SUCCESS_CREATE_PRICEBOOK_FIRST + ' ' + pricebook.Id + ' ' + Label.MESSAGE_SUCCESS_CREATE_SECOND;
        return new RF_Response_Message(Label.MESSAGE_SUCCESS_CODE, Label.MESSAGE_SUCCESS, result);
    }

    public static RF_Response_Message removeFromPriceBook(String recordId){
        Savepoint sp = Database.setSavepoint();
        try {
            List<Pricebook2> pricebooks = [SELECT Id, (SELECT Id FROM PricebookEntries) FROM Pricebook2 WHERE Id = :recordId];
            List<PricebookEntry> pricebookEntries = new List<PricebookEntry>();
            for(Pricebook2 p: pricebooks){
                pricebookEntries.addAll(p.PricebookEntries);

            }
            Database.delete(pricebookEntries);
            Database.delete(pricebooks);
        } catch(Exception e) {
            Database.rollback(sp);
            return new RF_Response_Message(Label.MESSAGE_ERROR_CODE, Label.MESSAGE_ERROR, e.getMessage());
        }
        return new RF_Response_Message(Label.MESSAGE_SUCCESS_CODE, Label.MESSAGE_SUCCESS, Label.MESSAGE_SUCCESS_DELETE_PRICEBOOK);
    }
}